name: Java CI

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          server-id: github
          java-version: 1.8

      # Gradle 缓存配置
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Deploy to Alibaba Package Registry
        run: gradle publish
        env:
          ALIBABA_MAVEN_USERNAME: 5f3fc340209ad8bf48f5dd13
          ALIBABA_MAVEN_PASSWORD: ${{ secrets.ALIYUN_PASSWORD }}
